export enum VerbAffix {
    Prefix = "prefix",
    PassivePrefix = "passive_prefix",
    PluralPrefix = "plural_prefix",
    PluralPassivePrefix = "plural_passive_prefix",
    GenitivePrefix = "gen_prefix",
    DativePrefix = "dat_prefix",
    AccusativePrefix = "acc_prefix",
    AblativePrefix = "abl_prefix",
    Suffix = "suffix",
    PassiveSuffix = "passive_suffix",
    PluralSuffix = "plural_suffix",
    PluralPassiveSuffix = "plural_passive_suffix",
    GenitiveSuffix = "gen_suffix",
    DativeSuffix = "dat_suffix",
    AccusativeSuffive = "acc_suffix",
    AblativeSuffix = "abl_suffix",
}
